CONF_FAST_POLL_INTERVAL = "fast_scan_interval"
CONF_ALLERGEN_DEFENDER_SWITCH = "allergen_defender_switch"
CONF_APP_ID = "app_id"
CONF_INIT_WAIT_TIME = "init_wait_time"
CONF_CREATE_SENSORS = "create_sensors"
CONF_CREATE_INVERTER_POWER = "create_inverter_power"
CONF_PII_IN_MESSAGE_LOGS = "pii_in_message_logs"
CONF_MESSAGE_DEBUG_LOGGING = "message_debug_logging"
CONF_LOG_MESSAGES_TO_FILE = "log_messages_to_file"
CONF_MESSAGE_DEBUG_FILE = "message_debug_file"
CONF_CLOUD_CONNECTION = "cloud_connection"

LENNOX_DEFAULT_CLOUD_APP_ID = "mapp079372367644467046827001"

LENNOX_DOMAIN = "lennoxs30"
LENNOX_MFG = "Lennox"
